# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf07ac99c8a2196fdbe4d2242c4fabaa69cdc335f2b8a15b2ce38cdecdea057a919e2e362f0ede6eb29c917b218ebb704b773eed07a3139898385ad538a9cbcd

test:
  secret_key_base: 8b3116a33b510a13082774fbef564e254853a2538f97003a8fe2bf5b26be24b7feea10c9ee53308c316bfb9b29b84990cd08e8c0e8c9d6cc75ecabeaad5d91ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
